language: node_js
cache:
  directories:
  - node_modules
node_js:
- node
script:
- npm run build
branches:
  only:
  - master
deploy:
  provider: npm
  skip_cleanup: true
  email: christoph@winzerhof-wurst.at
  on:
    tags: true
  api_key:
    secure: BxQxW2DfphS9IP2tjZhVQCPPlwvHIJVB4T8wOqQ8rExiQIEMDc5/7JNh5/R3HS1Vn4XT/wXTpa8Pnytqtnrcxv13qwj8BVfO2ccSHGG/mpYFRaVkJb2ov0THAydBh4ESWyxPmivCO3Xm9gyxjhWBJtBjBY/+I+NqCKLd6kVVF7PsnGb7Vl1VUcJ/0y2/81mw52TC3ZRdkLTOxGL6FhKCoHsK7UoSyh2d13Pw8IM+FTTCH2GIAAKUmsU/q0xzcZd3bZhy35X5tOdh/PB0IsvqUFodAPsZpl9g9sw7CQfgV0e3VdFo+p4lK8s8I5LHbJTlF0W9m5DVCghDJRTVuW5nhZWmPrdxEYV+ddqE29Hq1lORQSEKXWZnsrwxvhWsaykM4aLWr7KDh82KOewoR5fYLUxKHa6mKm2rFiZbwrurxWIJl8mkQGLhRnIgaJrSsRYjLOV3ljrrIrLDd43UlE4iN9OlgDZ93k+CNRkO/U+K1YJIflI9UNheyMTACtn/W7YwCGG7Uo27McGtZfafSOy3zcIthptMeAxRwDaGG9VGsxuXzpBoNTIb1iMlLV0K344E9SLmMngLZfgAkAidqCdzCRVPeBmy022oGC+fIy8sMSzNpSadzMeDK5jJx7wOA/hlBnqwNcyJFaEaZvdeQA1Pu/PWoRiNfGlsKljUlGX6krc=
