language: node_js
dist: xenial
sudo: false
node_js:
  - 11
cache:
  npm: true
  directories:
    - node_modules
script:
  - npm run build
  - npm run lint
  - npm run stylelint
deploy:
  provider: npm
  skip_cleanup: true
  email: skjnldsv@protonmail.com
  on:
    tags: true
env:
  global:
    secure: q3Myirpe8pxcp2dDbZZ+d4MPGQ8w5cWQz5OzX8rQqN6zehNMs1zHJWvlIB3G0Yp8koNq/uAMl+KNZybpM0Wtkr3NJeYBSjmZI+GhFWYywuwq88O4feypTV4r+pNh7UquO9pqcry6Pgd8QGlvnA6UByWxWCWjkgpQxX5nnqE3JIhwoTh80fp/O+QguZArPMRNlDz0DEuHVzoVWd7kjsYB9BFzFD09x/w7YmT22ni67usGThxO9v0YB4EUNY7jY46zSJ8U58FuKkVrFULUhO800xdNGyyqcYWOk0qnmdjafSu7tvHIwjzQOkv3U0jWJArCzE7Qwsx0aefZtv/CRAq5D2jIhfRYF+HVRS1P/hXsKY1ajW5ldhmS8m97Exlw5grn/tB/tCAgpcWYyvlMdcNOWjMlwJlshhlcpdh/44ao3hD81GdhWxkgII/eDNY0PHZNj+UsL1YOyFoMPYlLCcNJ3H1rADtFWZ49wdGejo1c0oGnti+lNikxd2Xq8XizkpWvOGDc7ysGscaLKUlGhXymqsBq31HYdLB7FhQWBTz+sf4tNzvgKE9CgwbLYVWcJ6dVF65dfPyTpZdTRGkhrSKOqZX09hptQFDx9s7XQJME0ilw4B7dwXpLGNkceXDejHvs7821UwX2XXVZ2s0bNJ1eEr7vjG/OBCZe/WQz+w8TaEY=
