language: node_js
cache:
  directories:
  - node_modules
node_js:
- node
script:
- npm run build
deploy:
  provider: npm
  skip_cleanup: true
  email: skjnldsv@protonmail.com
  on:
    tags: true
  api_key:
    secure: jrahLwnd9ORazjwE1JHdXCY/UGpqUuoymACnnKKDa97wWO3h7kBFndmWbU5zVmVuT8FZmpUpZQRJQWquWEw9unr+I1LPHgn4HSemwLI0HJ4pq/k4RBDRlg9E5oCv6AAl6rYGyuH6wUfsuG4hwsjJ58/rXplBnYckQKSRlRSTs2NxfUiHMzTL3SfzJy0/y8+rYehAARRy+zIwctsuKav/N+EbH7lYAqBZAVbHKcaIG0wepqMrbNaGIQkWMP5F8frqxcKtaHh+misznYAawE4afXj3x43N3TQN7sbTog42OQss/ped8/so8asV0PY6mz89kdKRYC+7NeGwO9OEVJUw2yqngtTEXPc71KqvG5nMVG/UHTd1BXfMmSPUNhXTjGQXzt2Dmttjvewg0IYEDtAtbTb8MTjGlesSdr53a6K28HHT7KUhpmueFEg0AhiFqnAiMmwhstwvNdJM3GwXFe5MHPE3gP+P8EUVk6R5heO5OhlkuzVJczaxk3fwSxZdGAjRy88lo9ZXlS4GA8GQqMTRDhS94l0tDISYJs1rTObxLmIsnM1F6fO8WkTGUxzidq7gdBKFJ4KAW6u36tO7MfgrfL2K6YW8hx575/S5Yk0aASpQd85y63yBBVXS9GmePw7wSDPgGhWhkHzg9lbrx2Q39Le59B922W5So1O+OI0da+g=
