language: node_js
cache:
  directories:
  - node_modules
node_js:
- node
script:
- npm run build
deploy:
  provider: npm
  skip_cleanup: true
  email: skjnldsv@protonmail.com
  on:
    tags: true
  api_key:
    secure: EvIM67pD7g1aB/EGqyGgb9EdsZMMifdtw/JGImROyztEOlfMAu9lePDdxNZ2y6bYCeFVv6gGmQnZhdTqt2ejlXcYZgJtHjdtGEHOnGYPE+QAr0rbMmtEAQuIBg0tFfrDUiS5uf5zxkDcBJIYVMZUGklBPVNn78ewVtfrPbhmMslG0xTYaIwdWE738jl2YKEVnunlZiSje1dlcRAIslTLSMHJW7R4dGFJtgWFzNWJ3c6NE81U3okpGTSOCwPXizuJ1VeKcrWRSXmhVev4NZ9x8KuQZ5laK/0+koN+RUVT/mS3MyH7YBzkpnKPrqV6kj7noq4cpJvFKPspz1W67GiFsML6Utom/3tACmrYkOcVSknh+sItA51Ly/36G/P90IdtZRWykfHdxnRHLsPJakgJul5Aj//p6gJwn593WhWv42ZiSEU0fsLGcM+saF3LoumOkZQV5LcHlNS5iA22KLHimeFM3gC/WI8S8mK0qvG0qxfMiz950jBh9Jc/pet/7RjNwIcPp6gG6b+FaG/zwG+4c6YxbLWCKO3t1BhQJStNAbpC3z83Glprp7tsUAwhPDUcO/+DQ/PpHAEATVRtE9aUwZNsI0dFiDVg5Dgkvll5OZr3/sd93JjfwK8KSp3gD8xbkYqDXQ3bicXDhDxx5+Jgk778LCA07LtL4TIEsTJ5elI=
