language: node_js
cache:
  directories:
  - node_modules
node_js:
- node
script:
- npm run build
deploy:
  provider: npm
  skip_cleanup: true
  email: christoph@winzerhof-wurst.at
  on:
    tags: true
  api_key:
    secure: JsV/5vVGLUcAN5y60jbWaVu01DQNV5EcREZMmtM/jfOC6MLM9Zgx/kjCR8YTQ62pup9Dg1mc6bGGqv1E1Nr08+Rh4/gHXaE42Cobe8pt+SZYpz5Oc8Z7PKdbD4VvQvm5C862oK51kyDw1ZhqMYayh2PwhLdQUIs0mBG65OID6YHlVU/fGtLL5Cx1i8INXrZTNwtO8tgg59JWRcHYHJAOM42uk9jhFGCDtVcJryUygHAFgJErssbp6j/C0LfmZ1qoZtclaA4NHBILp1r+BbhcYg++KxugSaRWRK7+ewo6v4QixAPmPiQpyQR1ZdJgd3vZdolnbJkZUJcARpzCBKwxGSqzyZpgXvzi7ccedLtxHfwstVAwQEIqLcOzlq7yeW9WCtBisSITmRA/PozgwrWM83Iq4DAkJKtBt78Vfy+sQn6KbnDQdji8nla6Df/VNRbdJUwqNNcsSN++vSVgYtsCGOiPPBhqEYNLfmwus2QsQ57lmPoqPza4moYUGI5l4tQ/HZ8V2iuiGMG2CRcpVtUzlBHRTX/kocD4wOiqJ5DUwhpRMHoY247buFLTMPnNzTC0p5cdpJtwb6Sjw/f2dUt6moqxgWS24HkBsRloucIEHYZ2/4tuJNY6ru1ufpWUVd035UCL7c+2vPB3SimiLAADH7xLF+tMVQ2pQgWGQZiakrw=
