language: node_js
cache:
  directories:
  - node_modules
node_js:
- node
script:
- npm run build
deploy:
  provider: npm
  skip_cleanup: true
  email: christoph@winzerhof-wurst.at
  on:
    tags: true
  api_key:
    secure: EJKd4Aa328eQjx5aiJnicasMpXXUTLy1tG+7GYtsBPCcs+AnQ72DhY3D5Qz1jpa1fxJ8R197xWcSE6CKJuRCtGgNODJ0pk4zy8MA17ia+aVF1ZxnmracqrYIVGY4DsW/NAip2Tw/hCY2ZG6nCvgvJ/6RaNYc4T2NampvqJG8QZNQh3j22NKeW7Dk73Vh0Af10uzDYCsuMLFeBUSWj8DZ3OHE+JCc8HunWwgfK/Vwa/E/tsixSvI09t+Vxuy4peW/oj5jH9iJjERJNn1SnrHb8rQSWUZZjEAqXiWcSipfyEbcVMHJmYZMFBjAdxIoUlB3H/kNsHzC04H54dJxbQfey6id5Qq8Wo82WseQz1+GiXQUxCbj9P0fGx/h8BGUrSHimLle7uliRpi7a6IwCUk/xIPl2Hc9DabJgZKb5f6lSOL0rRurCsZWynbpAtchnYh5SalRpYlHDYfQTOqYCNljGIMek2/Iyr11ZFmvfd73SiyQKmkCeDrWUpkb+bwHzuivIFPlutBAo7NwRowGCK3xVF29Blh3z6+yTOjZP2LGVGZuTICEBRoB8deolv5050N/505kUAPbLmwfCx+OUbM2QKvpUGJryBLyjrRUbeZa+qjICpVOvgKg+yybQUS8Hog+/WRkU9sMunLbBzoB5hwhtUA8rNH9pd5duY/HNX5wCFM=
