name: Changelog

on:
  pull_request:
    paths:
      - 'package.json'

jobs:
  build:
    name: Auto generation
    runs-on: ubuntu-latest
    steps:
      - name: Check-out
        uses: actions/checkout@v3

      - name: Get last released tag
        id: last_version
        uses: InsonusK/get-latest-release@v1.1.0
        with:
          myToken: ${{ secrets.GITHUB_TOKEN }}
          exclude_types: draft
          view_top: 1

      # Returns the version without a leading v
      - name: Get new version
        id: future_version
        uses: Saionaro/extract-package-version@v1.2.1

      - name: Generate changelog between ${{ steps.last_version.outputs.tag_name }} and v${{ steps.future_version.outputs.version }}
        uses: docker://ferrarimarco/github-changelog-generator
        # If we have a version change
        if: steps.last_version.outputs.tag_name != format('{{v{0}}}', steps.future_version.outputs.version)
        with:
          args: >
            -t ${{ secrets.GITHUB_TOKEN }}
            --user nextcloud
            --project nextcloud-vue
            --no-issues
            --no-issues-wo-labels
            --max-issues 0
            --exclude-labels "duplicate,question,invalid,wontfix,dependencies"
            --since-tag ${{ steps.last_version.outputs.tag_name }}
            --future-release v${{ steps.future_version.outputs.version }}
            --breaking-label "### :boom: Breaking changes"
            --enhancement-label "### :rocket: Enhancements"
            --bugs-label "### :bug: Fixed bugs"
            --deprecated-label "### Deprecated"
            --removed-label "### Removed"
            --security-label "### Security fixes"
            --issues-label "### Closed issues"
            --pr-label "### Closed pull requests"

      - name: Print changelog to console
        run: cat CHANGELOG.md

      - name: Upload changelog
        uses: actions/upload-artifact@v3
        with:
          name: Changelog
          path: CHANGELOG.md
