name: Test

on:
  pull_request:
    branches:
      - master
      - stable*

jobs:
  jest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [11.x]
    steps:
      - uses: actions/checkout@v1
      - name: Setup node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      - name: Test
        run: npm run test
        env:
          CI: true
