name: Update server styling

on:
  workflow_dispatch:
  schedule:
    - cron: "0 5 * * *"

jobs:
  server-styling-update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Download css
        run: |
          cd nextcloud-vue/styleguide/assets
          curl https://nextcloud.github.io/server/apps/theming/css/default.css --output default.css
          # Fix icons css import
          curl https://nextcloud.github.io/server/core/css/server.css | sed 's|../../dist/icons.css|icons.css|g' > server.css
          curl https://nextcloud.github.io/server/dist/icons.css --output icons.css

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.COMMAND_BOT_PAT }}
          commit-message: Update styling from server
          committer: GitHub <noreply@github.com>
          author: nextcloud-command <nextcloud-command@users.noreply.github.com>
          signoff: true
          branch: automated/noid/server-styling-update
          title: Automated styling update from server
          body: |
            Auto-generated update of our locally cached css styling from
             * https://nextcloud.github.io/server/apps/theming/css/default.css
             * https://nextcloud.github.io/server/core/css/server.css
          labels: |
            dependencies
            3. to review
